import logging

logger = logging.getLogger(__name__)

async def run_agent_pipeline(system_prompt: str, user_audio_path: str = None, user_text: str = None) -> str:
    logger.info(f"Running pipeline with prompt: {system_prompt[:30]}...")
    
    if user_text:
        logger.info(f"User Text: {user_text}")
    if user_audio_path:
        logger.info(f"User Audio Path: {user_audio_path}")
        
    return "This is a response generated by the modular Pipecat pipeline."
